default_context:
  project_name: 'HistoCAT'
  project_slug: 'histocat'
  domain_main: 'histocat.net'
  domain_staging: 'staging.histocat.net'
  docker_swarm_stack_name_main: 'histocat-net'
  docker_swarm_stack_name_staging: 'staging-histocat-net'
  secret_key: 'changethis'
  first_superuser: 'anton.rau@gmail.com'
  first_superuser_password: 'changethis'
  backend_cors_origins: 'http://localhost, http://localhost:4200, http://localhost:3000, http://localhost:8080, https://localhost, https://localhost:4200, https://localhost:3000, https://localhost:8080, http://dev.histocat.net, https://staging.histocat.net, https://histocat.net, http://local.dockertoolbox.tiangolo.com, http://localhost.tiangolo.com'
  smtp_port: '587'
  smtp_host: 'smtp.sendgrid.com'
  smtp_user: 'plankter'
  smtp_password: 'changethis'
  smtp_emails_from_email: 'support@histocat.net'
  postgres_password: 'changethis'
  pgadmin_default_user: 'anton.rau@gmail.com'
  pgadmin_default_user_password: 'changethis'
  traefik_constraint_tag: 'histocat.net'
  traefik_constraint_tag_staging: 'staging.histocat.net'
  traefik_public_network: 'traefik-public'
  traefik_public_constraint_tag: 'traefik-public'
  sentry_dsn: ''
  docker_image_prefix: 'plankter/histocat-'
  docker_image_backend: 'plankter/histocat-backend'
  docker_image_worker: 'plankter/histocat-worker'
  docker_image_frontend: 'plankter/histocat-frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
