version: '3.3'
services:
  db:
    env_file:
      - env-postgres.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
  backend:
    env_file:
      - env-postgres.env
      - env-backend.env
    environment:
      - SERVER_NAME=${DOMAIN}
      - SERVER_HOST=https://${DOMAIN}
  celeryworker:
    env_file:
      - env-postgres.env
      - env-backend.env
    environment:
      - SERVER_HOST=https://${DOMAIN}
