version: '3.3'
services:
  proxy:
    command: --docker \
      --docker.watch \
      --docker.exposedbydefault=false \
      --constraints=tag==${TRAEFIK_TAG} \
      --logLevel=DEBUG \
      --accessLog \
      --web
  # backend:
  #   command: bash -c "while true; do sleep 1; done"  # Infinite loop to keep container live doing nothing
  backend:
    command: /start-reload.sh
