site_name: histoCAT Web

copyright: Copyright &copy; 2021 Anton Rau
repo_url: https://github.com/BodenmillerGroup/histocat-web
site_url: https://bodenmillergroup.github.io/histocat-web

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.tabs
    - navigation.top
    - navigation.expand

markdown_extensions:
  - admonition
  - footnotes

plugins:
  - include-markdown
  - search

nav:
  - Home:
    - index.md
    - changelog.md
    - license.md
  - User manual:
    - user/registration.md
    - user/structure.md
    - user/groups.md
    - user/projects.md
    - Project Workspace:
      - user/project.md
      - user/slides.md
      - user/channels.md
      - user/image.md
      - user/tiles.md
      - user/region.md
      - user/histogram.md
      - user/presets.md
      - user/settings.md
      - user/datasets.md
      - user/segmentation.md
      - user/pipelines.md
      - user/results.md
      - user/gating.md
    - Admin Views:
      - user/users.md
      - user/models.md
  - Developer documentation:
    - dev/overview.md
    - dev/development.md
    - dev/staging.md
    - dev/production.md
