[build-system]
requires = ["poetry>=1.0.5"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "histocat"
version = "2020.04.22"
description = "HistoCAT for Web"
authors = ["Anton Rau <anton.rau@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
aiofiles = "^0.5.0"
aioredis = {version = "^1.3.1", extras = ["hiredis"]}
alembic = { version = "^1.4.2", optional = true }
dramatiq = { version = "^1.8.1", extras = ["rabbitmq", "watch"] }
email-validator = "^1.1.0"
emails = "^0.5.15"
fastapi = "^0.54.2"
fastobo = "^0.7.2"
flatbuffers = "^1.12"
flatten-dict = "^0.3.0"
fsspec = "^0.7.3"
gunicorn = { version = "^20.0.4", optional = true }
imctools = { git = "https://github.com/BodenmillerGroup/imctools.git", branch="next" }  # "^1.0.7"
jinja2 = "^2.11.2"
mahotas = "^1.4.9"
matplotlib = "^3.2.1"
opencv-python-headless = "^4.2.0.34"
orjson = "^3.0.0"
pandas = "^1.0.3"
passlib = { version = "^1.7.2", extras = ["bcrypt"] }
phenograph = { git = "https://github.com/jacoblevine/phenograph.git" }  # "^1.5.5"
psycopg2-binary = "^2.8.4"
ptvsd = "^4.3.2"
pyarrow = "^0.17.0"
pydevd-pycharm = "^201.*"
PyJWT = "^1.7.1"
python-multipart = { version = "^0.0.5", optional = true }
PyYAML = "^5.3.1"
redis = { version = "^3.5.2", extras = ["hiredis"] }
requests = "^2.23.0"
scanpy = "^1.4.6"
scikit-image = "^0.17.2"
scikit-learn = "^0.23.0"
shapely = "^1.7.0"
SQLAlchemy = "^1.3.17"
tables = "^3.6.1"
tenacity = "^6.2.0"
ujson = "^2.0.3"
umap-learn = "0.4.3"
uvicorn = { version = "^0.11.5", optional = true }

[tool.poetry.dev-dependencies]
autoflake = "^1.3.1"
black = "^19.10b0"
flake8 = "^3.8.1"
isort = "^4.3.21"
mypy = "^0.770"
pylint = "^2.5.2"
pytest = "^5.4.2"
sqlalchemy-stubs = "^0.3"
vulture = "^1.4"

[tool.poetry.extras]
backend = [ "alembic", "python-multipart", "gunicorn", "uvicorn" ]
worker = []

[tool.black]
line-length = 120
target-version = [ "py38" ]
