[build-system]
requires = ["poetry>=1.0.10"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "histocat"
version = "2020.09.30"
description = "histoCAT for Web"
authors = ["Anton Rau <anton.rau@uzh.ch>"]

[tool.poetry.dependencies]
python = "^3.8"
aiofiles = "^0.5.0"
aioredis = { version = "^1.3.1", extras = ["hiredis"] }
alembic = { version = "^1.4.3", optional = true }
dramatiq = { version = "^1.9.0", extras = ["rabbitmq", "watch"] }
email-validator = "^1.1.1"
emails = "^0.6"
fastapi = "^0.61.1"
gunicorn = { version = "^20.0.4", optional = true }
imctools = "^2.0.1"  # "^1.0.8"
jinja2 = "^2.11.2"
mahotas = "^1.4.11"
matplotlib = "^3.3.1"
opencv-python-headless = "^4.4.0.44"
orjson = "^3.4.0"
pandas = "^1.1.2"
passlib = { version = "^1.7.2", extras = ["bcrypt"] }
phenograph = "1.5.3"  # { git = "https://github.com/jacoblevine/phenograph.git" }
psycopg2-binary = "^2.8.6"
ptvsd = "^4.3.2"
pyarrow = "^1.0.1"
pydevd-pycharm = "^203.*"
PyJWT = "^1.7.1"
pynndescent = "^0.5.0"
python-multipart = { version = "^0.0.5", optional = true }
redis = { version = "^3.5.3", extras = ["hiredis"] }
requests = "^2.24.0"
scanpy = "^1.6.0"
scikit-image = "^0.17.2"
scikit-learn = "^0.23.2"
SQLAlchemy = "^1.3.19"
tables = "^3.6.1"
tenacity = "^6.2.0"
ujson = "^3.2.0"
umap-learn = "0.4.4"
uvicorn = { version = "^0.12.1", extras = ["standard"], optional = true }

[tool.poetry.dev-dependencies]
autoflake = "^1.4"
black = "^19.10b0"
flake8 = "^3.8.3"
isort = "^5.5.4"
mypy = "*"
pylint = "^2.6.0"
pytest = "^6.1.0"
sqlalchemy-stubs = "^0.3"
vulture = "^2.1"

[tool.poetry.extras]
backend = ["alembic", "python-multipart", "gunicorn", "uvicorn"]
worker = []

[tool.black]
line-length = 120
target-version = ["py38"]
