version: '3.7'
services:
  db:
    volumes:
      - app-db-data:/var/lib/postgresql/data
    deploy:
      placement:
        constraints:
          - node.labels.${STACK_NAME}.app-db-data == true
  proxy:
    deploy:
      placement:
        constraints:
          - node.role == manager

  portainer:
    volumes:
      - portainer-data:/data
    deploy:
      placement:
        constraints:
          - node.labels.${STACK_NAME}.portainer_data == true

volumes:
  app-db-data:
  portainer-data:
