version: '3.7'
services:
  backend:
    restart: "no"
    build:
      context: ../backend
      dockerfile: backend.dockerfile
      args:
        BACKEND_ENV: development
    command: /app/bin/start-reload.sh
    ports:
      - 5678:5678
    volumes:
      - ../backend/app:/app

  worker:
    restart: "no"
    build:
      context: ../backend
      dockerfile: worker.dockerfile
      args:
        BACKEND_ENV: development
    ports:
      - 5688:5688
    volumes:
      - ../backend/app:/app

  frontend:
    restart: "no"
    build:
      context: ../frontend
      args:
        FRONTEND_ENV: development

  proxy:
    command: --docker \
      --docker.watch \
      --docker.exposedbydefault=false \
      --constraints=tag==${TRAEFIK_TAG} \
      --logLevel=DEBUG \
      --accessLog \
      --api
