version: '3.7'
services:
  backend:
    restart: "no"
    build:
      context: ../backend
      dockerfile: backend.dockerfile
      args:
        BACKEND_ENV: development
    command: /start-reload.sh
    volumes:
      - ../backend/app:/app

  celeryworker:
    restart: "no"
    build:
      context: ../backend
      dockerfile: celeryworker.dockerfile
      args:
        BACKEND_ENV: development
    environment:
      - RUN=celery worker -A app.worker -l info -Q main-queue -c 1
    volumes:
      - ../backend/app:/app

  frontend:
    restart: "no"
    build:
      context: ../frontend
      args:
        FRONTEND_ENV: development

  proxy:
    command: --docker \
      --docker.watch \
      --docker.exposedbydefault=false \
      --constraints=tag==${TRAEFIK_TAG} \
      --logLevel=DEBUG \
      --accessLog \
      --api
