version: '3.7'
services:
  db:
    ports:
      - 5432:5432
  pgadmin:
    ports:
      - 5050:5050
  proxy:
    ports:
      - 80:80
      - 8090:8080
  flower:
    ports:
      - 5555:5555
  backend:
    ports:
      - 8888:8888
      - 5678:5678
  portainer:
    ports:
      - 9000:9000
