version: '3.7'
services:
  backend:
    restart: always
    image: ${DOCKER_IMAGE_BACKEND}:${TAG-latest}

  celeryworker:
    restart: always
    image: ${DOCKER_IMAGE_CELERYWORKER}:${TAG-latest}

  frontend:
    restart: always
    image: ${DOCKER_IMAGE_FRONTEND}:${TAG-latest}

  proxy:
    command: --docker \
      --docker.watch \
      --docker.exposedbydefault=false \
      --constraints=tag==${TRAEFIK_TAG} \
      --logLevel=INFO \
      --accessLog \
      --api
