version: '3.7'
services:
  backend:
    restart: always
    image: ${DOCKER_IMAGE_BACKEND}:${TAG-latest}
    environment:
      - SMTP_PASSWORD
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
        tag: backend

  worker:
    restart: always
    image: ${DOCKER_IMAGE_WORKER}:${TAG-latest}
    environment:
      - SMTP_PASSWORD
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
        tag: worker

  frontend:
    restart: always
    image: ${DOCKER_IMAGE_FRONTEND}:${TAG-latest}

  proxy:
    command: --docker \
      --docker.watch \
      --docker.exposedbydefault=false \
      --constraints=tag==${TRAEFIK_TAG} \
      --logLevel=INFO \
      --accessLog \
      --api
