version: '3.7'
services:
  backend:
    env_file:
      - env-postgres.env
      - env-backend.env
    environment:
      - SERVER_NAME=${DOMAIN}
      - SERVER_HOST=${PROTOCOL}://${DOMAIN}
    depends_on:
      - db
      - rabbitmq
      - redis
    volumes:
      - app-data:/data
    labels:
      - traefik.frontend.rule=PathPrefix:/api,/docs,/redoc
      - traefik.enable=true
      - traefik.port=80
      - traefik.tags=${TRAEFIK_TAG}
    networks:
      default:
        aliases:
          - ${DOMAIN}

  worker:
    env_file:
      - env-postgres.env
      - env-backend.env
    environment:
      - SERVER_HOST=${PROTOCOL}://${DOMAIN}
    depends_on:
      - db
      - rabbitmq
      - redis
    volumes:
      - app-data:/data

  frontend:
    labels:
      - traefik.frontend.rule=PathPrefix:/
      - traefik.enable=true
      - traefik.port=80
      - traefik.tags=${TRAEFIK_TAG}

  db:
    restart: always
    image: postgres:11.3-alpine
    env_file:
      - env-postgres.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - app-db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  rabbitmq:
    restart: always
    image: rabbitmq:3.7.15-alpine
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  redis:
    restart: always
    image: redis:5.0.5-alpine3.9
    env_file:
      - env-redis.env
    volumes:
      - redis-data:/data

  pgadmin:
    restart: always
    image: dpage/pgadmin4
    depends_on:
      - db
    env_file:
      - env-pgadmin.env
    ports:
      - 5050:5050
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  portainer:
    restart: always
    image: portainer/portainer:1.21.0
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    ports:
      - 9000:9000

  proxy:
    restart: always
    image: traefik:v1.7.12-alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 443:443
      - 8090:8080

volumes:
  app-data:
  app-db-data:
  portainer-data:
  redis-data:
  rabbitmq-data:
  pgadmin-data:
