[tool.poetry]
name = "histocat"
version = "0.1.0"
description = "HistoCAT for Web"
authors = ["Anton Rau <anton.rau@gmail.com>"]

[tool.poetry.dependencies]
python = "3.7.*"
alembic = "^1.0"
cached-property = "^1.5.1"
celery = "^4.3.0"
email-validator = "^1.0"
emails = "^0.5.15"
fastapi = "^0.20.0"
GeoAlchemy2 = "^0.6.1"
gunicorn = "^19.9"
h5py = "^2.9"
imctools = { git = "https://github.com/BodenmillerGroup/imctools.git", branch = "master" }
jinja2 = "^2.10"
lxml = "^4.3"
mahotas = "^1.4"
opencv-python-headless = "^4.1"
pandas = "^0.24.2"
psycopg2-binary = "^2.8"
passlib = {version = "^1.7",extras = ["bcrypt"]}
pyjwt = "^1.7"
python-multipart = "^0.0.5"
PyYAML = "^5.1"
raven = "^6.10"
requests = "^2.21"
scikit-image = "^0.15.0"
Shapely = "^1.6"
sqlalchemy = "^1.3"
tables = "^3.5"
tenacity = "^5.0"
uvicorn = "^0.7.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.7"
ptvsd = "^4.2"
pydevd-pycharm = "^191.6605"
pytest = "^4.4"
vulture = "^1.0"
mypy = "^0.701.0"
autoflake = "^1.3"
isort = "^4.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
