version: '3.7'
services:
  backend:
    image: '${DOCKER_IMAGE_BACKEND_STAGING}:${DOCKER_TAG-latest}'
    build:
      context: ../backend
      dockerfile: backend.dockerfile
      args:
        BACKEND_ENV: staging
        PROTOCOL: ${PROTOCOL}
        DOMAIN: ${DOMAIN_STAGE}

  worker:
    image: '${DOCKER_IMAGE_WORKER_STAGING}:${DOCKER_TAG-latest}'
    build:
      context: ../backend
      dockerfile: worker.dockerfile
      args:
        BACKEND_ENV: staging
        PROTOCOL: ${PROTOCOL}
        DOMAIN: ${DOMAIN_STAGE}

  frontend:
    image: '${DOCKER_IMAGE_FRONTEND_STAGING}:${DOCKER_TAG-latest}'
    build:
      context: ../frontend
      args:
        VUE_APP_NAME: ${VUE_APP_NAME}
        VUE_APP_PROTOCOL: ${VUE_APP_PROTOCOL}
        VUE_APP_DOMAIN: ${DOMAIN_STAGE}
