version: '3.7'
services:
  backend:
    image: '${DOCKER_IMAGE_BACKEND}:${DOCKER_TAG-latest}'
    build:
      context: ../backend
      dockerfile: backend.dockerfile
      args:
        BACKEND_ENV: production
        PROTOCOL: ${PROTOCOL}
        DOMAIN: ${DOMAIN_PROD}

  worker:
    image: '${DOCKER_IMAGE_WORKER}:${DOCKER_TAG-latest}'
    build:
      context: ../backend
      dockerfile: worker.dockerfile
      args:
        BACKEND_ENV: production
        PROTOCOL: ${PROTOCOL}
        DOMAIN: ${DOMAIN_PROD}

  frontend:
    image: '${DOCKER_IMAGE_FRONTEND}:${DOCKER_TAG-latest}'
    build:
      context: ../frontend
      args:
        VUE_APP_NAME: ${VUE_APP_NAME}
        VUE_APP_PROTOCOL: ${VUE_APP_PROTOCOL}
        VUE_APP_DOMAIN: ${DOMAIN_PROD}
