version: '3.7'
services:
  backend:
    restart: "no"
    build:
      context: ../backend
      dockerfile: backend.dockerfile
      args:
        BACKEND_ENV: development
        PROTOCOL: ${PROTOCOL}
        DOMAIN: ${DOMAIN_DEV}
    command: /app/bin/start-reload.sh
    ports:
      - 5678:5678
    volumes:
      - ../backend:/app

  worker:
    restart: "no"
    build:
      context: ../backend
      dockerfile: worker.dockerfile
      args:
        BACKEND_ENV: development
        PROTOCOL: ${PROTOCOL}
        DOMAIN: ${DOMAIN_DEV}
    ports:
      - 5688:5688
    volumes:
      - ../backend:/app

  frontend:
    restart: "no"
    build:
      context: ../frontend
      args:
        VUE_APP_NAME: ${VUE_APP_NAME}
        VUE_APP_PROTOCOL: ${VUE_APP_PROTOCOL}
        VUE_APP_DOMAIN: ${DOMAIN_DEV}


  proxy:
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--api.debug=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - "--entrypoints.web.address=:80"
