version: "3.7"
services:
  backend:
    restart: always
    image: ${DOCKER_IMAGE_BACKEND}:${DOCKER_TAG-latest}
    environment:
      - SMTP_PASSWORD

  worker:
    restart: always
    image: ${DOCKER_IMAGE_WORKER}:${DOCKER_TAG-latest}
    environment:
      - SMTP_PASSWORD

  frontend:
    restart: always
    image: ${DOCKER_IMAGE_FRONTEND}:${DOCKER_TAG-latest}

  proxy:
    command:
      - "--log.level=INFO"
      - "--api.insecure=false"
      - "--api.debug=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
