version: '3.7'
services:
  backend:
    restart: always
    image: ${DOCKER_IMAGE_BACKEND}:${TAG-latest}
    environment:
      - SMTP_PASSWORD

  worker:
    restart: always
    image: ${DOCKER_IMAGE_WORKER}:${TAG-latest}
    environment:
      - SMTP_PASSWORD

  frontend:
    restart: always
    image: ${DOCKER_IMAGE_FRONTEND}:${TAG-latest}
    args:
      VUE_APP_NAME: ${VUE_APP_NAME}
      VUE_APP_PROTOCOL: ${VUE_APP_PROTOCOL}
      VUE_APP_DOMAIN: ${DOMAIN_PROD}

  proxy:
    command:
      - "--log.level=INFO"
      - "--api.insecure=false"
      - "--api.debug=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
