version: "3.7"
services:
  backend:
    restart: always
    build:
      context: ../backend
      dockerfile: backend.dockerfile
      args:
        BACKEND_ENV: production
        PROTOCOL: ${PROTOCOL}
        DOMAIN: ${DOMAIN}

  worker:
    restart: always
    build:
      context: ../backend
      dockerfile: worker.dockerfile
      args:
        BACKEND_ENV: production
        PROTOCOL: ${PROTOCOL}
        DOMAIN: ${DOMAIN}

  frontend:
    restart: always
    build:
      context: ../frontend
      args:
        VUE_APP_NAME: ${PROJECT_NAME}

  proxy:
    command:
      - "--log.level=INFO"
      - "--api.insecure=false"
      - "--api.debug=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
