version: "3.7"
services:
  backend:
    restart: "no"
    build:
      context: ../backend
      dockerfile: backend.dockerfile
      args:
        BACKEND_ENV: staging
        PROTOCOL: ${PROTOCOL}
        DOMAIN: ${DOMAIN_STAGE}
    environment:
      - SMTP_PASSWORD

  worker:
    restart: "no"
    build:
      context: ../backend
      dockerfile: worker.dockerfile
      args:
        BACKEND_ENV: staging
        PROTOCOL: ${PROTOCOL}
        DOMAIN: ${DOMAIN_STAGE}

  frontend:
    restart: "no"
    build:
      context: ../frontend
      args:
        VUE_APP_NAME: ${VUE_APP_NAME}
        VUE_APP_PROTOCOL: ${VUE_APP_PROTOCOL}
        VUE_APP_DOMAIN: ${DOMAIN_STAGE}

  proxy:
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--api.debug=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
