name: docs
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material==7.1.8 mkdocs-include-markdown-plugin==3.1.3
      - run: mkdocs gh-deploy --force
